version: '3.7'

services:

  php-fpm:
    build:
      target: development
    environment:
      XDEBUG_CONFIG: client_host=localhost
      PHP_IDE_CONFIG: serverName=DegustaBox
    volumes:
      - ./Api:/opt/app

  nginx:
    ports:
      - 80:80
